[2023-06-05T08:57:00.761+0000] {processor.py:154} INFO - Started process (PID=32) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T08:57:00.769+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T08:57:00.778+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:57:00.778+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T08:57:01.106+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:57:01.097+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T08:57:01.107+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T08:57:01.150+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.408 seconds
[2023-06-05T08:57:31.668+0000] {processor.py:154} INFO - Started process (PID=109) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T08:57:31.672+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T08:57:31.673+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:57:31.673+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T08:57:31.732+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:57:31.730+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T08:57:31.733+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T08:57:31.750+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.087 seconds
[2023-06-05T08:58:02.108+0000] {processor.py:154} INFO - Started process (PID=173) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T08:58:02.111+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T08:58:02.112+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:58:02.112+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T08:58:02.167+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:58:02.165+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T08:58:02.168+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T08:58:02.192+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.091 seconds
[2023-06-05T08:58:32.686+0000] {processor.py:154} INFO - Started process (PID=237) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T08:58:32.690+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T08:58:32.692+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:58:32.692+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T08:58:32.750+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:58:32.748+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T08:58:32.751+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T08:58:32.775+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.099 seconds
[2023-06-05T08:59:03.293+0000] {processor.py:154} INFO - Started process (PID=292) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T08:59:03.296+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T08:59:03.299+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:59:03.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T08:59:03.470+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:59:03.459+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T08:59:03.472+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T08:59:03.548+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.261 seconds
[2023-06-05T08:59:33.740+0000] {processor.py:154} INFO - Started process (PID=354) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T08:59:33.742+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T08:59:33.744+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:59:33.743+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T08:59:33.896+0000] {logging_mixin.py:120} INFO - [2023-06-05T08:59:33.886+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T08:59:33.898+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T08:59:33.926+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.190 seconds
[2023-06-05T09:00:04.073+0000] {processor.py:154} INFO - Started process (PID=417) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T09:00:04.075+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T09:00:04.078+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:00:04.077+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T09:00:04.167+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:00:04.164+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T09:00:04.168+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T09:00:04.210+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.152 seconds
[2023-06-05T09:00:34.326+0000] {processor.py:154} INFO - Started process (PID=472) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T09:00:34.328+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T09:00:34.329+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:00:34.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T09:00:34.502+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:00:34.496+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T09:00:34.503+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T09:00:34.526+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.204 seconds
[2023-06-05T09:01:04.617+0000] {processor.py:154} INFO - Started process (PID=536) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T09:01:04.619+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T09:01:04.621+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:01:04.621+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T09:01:04.730+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:01:04.727+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T09:01:04.731+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T09:01:04.773+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.161 seconds
[2023-06-05T09:01:35.384+0000] {processor.py:154} INFO - Started process (PID=598) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T09:01:35.386+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T09:01:35.387+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:01:35.387+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T09:01:35.441+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:01:35.437+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T09:01:35.442+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T09:01:35.466+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.086 seconds
[2023-06-05T09:02:06.103+0000] {processor.py:154} INFO - Started process (PID=662) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T09:02:06.185+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T09:02:06.188+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:02:06.188+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T09:02:06.303+0000] {logging_mixin.py:120} INFO - [2023-06-05T09:02:06.299+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T09:02:06.306+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T09:02:06.335+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.243 seconds
[2023-06-05T10:02:18.725+0000] {processor.py:154} INFO - Started process (PID=708) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T10:02:18.729+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T10:02:18.736+0000] {logging_mixin.py:120} INFO - [2023-06-05T10:02:18.735+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T10:02:18.906+0000] {logging_mixin.py:120} INFO - [2023-06-05T10:02:18.900+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T10:02:18.906+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T10:02:18.944+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.236 seconds
[2023-06-05T11:26:09.695+0000] {processor.py:154} INFO - Started process (PID=771) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T11:26:09.696+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T11:26:09.697+0000] {logging_mixin.py:120} INFO - [2023-06-05T11:26:09.697+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T11:26:09.751+0000] {logging_mixin.py:120} INFO - [2023-06-05T11:26:09.749+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T11:26:09.752+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T11:26:09.770+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.079 seconds
[2023-06-05T12:47:16.644+0000] {processor.py:154} INFO - Started process (PID=835) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T12:47:16.645+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T12:47:16.646+0000] {logging_mixin.py:120} INFO - [2023-06-05T12:47:16.646+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T12:47:16.686+0000] {logging_mixin.py:120} INFO - [2023-06-05T12:47:16.684+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T12:47:16.687+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T12:47:16.701+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.060 seconds
[2023-06-05T13:45:31.439+0000] {processor.py:154} INFO - Started process (PID=890) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T13:45:31.448+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T13:45:31.455+0000] {logging_mixin.py:120} INFO - [2023-06-05T13:45:31.455+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T13:45:31.727+0000] {logging_mixin.py:120} INFO - [2023-06-05T13:45:31.723+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T13:45:31.728+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T13:45:31.774+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.344 seconds
[2023-06-05T14:52:52.851+0000] {processor.py:154} INFO - Started process (PID=953) to work on /opt/airflow/dags/user_processing.py
[2023-06-05T14:52:52.855+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-05T14:52:52.857+0000] {logging_mixin.py:120} INFO - [2023-06-05T14:52:52.857+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-05T14:52:52.989+0000] {logging_mixin.py:120} INFO - [2023-06-05T14:52:52.980+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-06-05T14:52:52.991+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-05T14:52:53.029+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.184 seconds
