[2023-07-26T06:37:41.645+0000] {processor.py:154} INFO - Started process (PID=33) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:37:41.657+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:37:41.658+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:37:41.658+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:37:41.884+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:37:41.881+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:37:41.885+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:37:41.948+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.308 seconds
[2023-07-26T06:38:12.563+0000] {processor.py:154} INFO - Started process (PID=107) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:38:12.565+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:38:12.567+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:38:12.567+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:38:12.613+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:38:12.611+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:38:12.614+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:38:12.642+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.084 seconds
[2023-07-26T06:38:43.153+0000] {processor.py:154} INFO - Started process (PID=173) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:38:43.155+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:38:43.156+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:38:43.156+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:38:43.198+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:38:43.197+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:38:43.199+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:38:43.216+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.068 seconds
[2023-07-26T06:39:13.403+0000] {processor.py:154} INFO - Started process (PID=237) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:39:13.404+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:39:13.405+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:39:13.405+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:39:13.444+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:39:13.442+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:39:13.445+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:39:13.460+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2023-07-26T06:39:43.628+0000] {processor.py:154} INFO - Started process (PID=292) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:39:43.631+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:39:43.633+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:39:43.632+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:39:43.711+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:39:43.709+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:39:43.711+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:39:43.734+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.113 seconds
[2023-07-26T06:40:14.256+0000] {processor.py:154} INFO - Started process (PID=356) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:40:14.260+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:40:14.262+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:40:14.261+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:40:14.325+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:40:14.320+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:40:14.326+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:40:14.347+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.098 seconds
[2023-07-26T06:40:44.977+0000] {processor.py:154} INFO - Started process (PID=421) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:40:44.980+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:40:44.981+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:40:44.981+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:40:45.034+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:40:45.033+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:40:45.035+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:40:45.055+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.084 seconds
[2023-07-26T06:41:15.345+0000] {processor.py:154} INFO - Started process (PID=486) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:41:15.372+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:41:15.375+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:41:15.375+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:41:16.303+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:41:16.289+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:41:16.305+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:41:16.347+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 1.007 seconds
[2023-07-26T06:41:46.929+0000] {processor.py:154} INFO - Started process (PID=545) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:41:46.931+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:41:46.932+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:41:46.931+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:41:47.055+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:41:47.051+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:41:47.056+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:41:47.091+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.165 seconds
[2023-07-26T06:42:17.988+0000] {processor.py:154} INFO - Started process (PID=610) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:42:17.990+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:42:17.991+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:42:17.991+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:42:18.103+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:42:18.096+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:42:18.105+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:42:18.143+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.158 seconds
[2023-07-26T06:42:49.065+0000] {processor.py:154} INFO - Started process (PID=674) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:42:49.069+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:42:49.071+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:42:49.071+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:42:49.121+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:42:49.119+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:42:49.123+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:42:49.137+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.079 seconds
[2023-07-26T06:43:19.326+0000] {processor.py:154} INFO - Started process (PID=738) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:43:19.327+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:43:19.328+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:43:19.328+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:43:19.368+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:43:19.366+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:43:19.369+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:43:19.391+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.068 seconds
[2023-07-26T06:43:49.766+0000] {processor.py:154} INFO - Started process (PID=802) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:43:49.768+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:43:49.769+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:43:49.769+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:43:49.808+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:43:49.806+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:43:49.809+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:43:49.823+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.060 seconds
[2023-07-26T06:44:20.016+0000] {processor.py:154} INFO - Started process (PID=864) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:44:20.017+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:44:20.018+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:44:20.018+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:44:20.055+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:44:20.053+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:44:20.056+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:44:20.071+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.057 seconds
[2023-07-26T06:44:50.203+0000] {processor.py:154} INFO - Started process (PID=921) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:44:50.204+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:44:50.205+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:44:50.205+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:44:50.250+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:44:50.248+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:44:50.251+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:44:50.268+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.068 seconds
[2023-07-26T06:45:20.544+0000] {processor.py:154} INFO - Started process (PID=985) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:45:20.546+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:45:20.548+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:45:20.548+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:45:20.596+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:45:20.594+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:45:20.597+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:45:20.613+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.073 seconds
[2023-07-26T06:45:51.642+0000] {processor.py:154} INFO - Started process (PID=1048) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:45:51.645+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:45:51.646+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:45:51.646+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:45:51.682+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:45:51.680+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:45:51.683+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:45:51.702+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.063 seconds
[2023-07-26T06:46:22.127+0000] {processor.py:154} INFO - Started process (PID=1112) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:46:22.129+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:46:22.130+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:46:22.130+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:46:22.178+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:46:22.177+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:46:22.179+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:46:22.195+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.073 seconds
[2023-07-26T06:46:52.401+0000] {processor.py:154} INFO - Started process (PID=1177) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:46:52.404+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:46:52.405+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:46:52.405+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:46:52.458+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:46:52.456+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:46:52.459+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:46:52.479+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.081 seconds
[2023-07-26T06:47:22.952+0000] {processor.py:154} INFO - Started process (PID=1241) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:47:22.954+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:47:22.955+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:47:22.955+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:47:22.995+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:47:22.993+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:47:22.995+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:47:23.010+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2023-07-26T06:47:53.175+0000] {processor.py:154} INFO - Started process (PID=1297) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:47:53.178+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:47:53.179+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:47:53.179+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:47:53.220+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:47:53.217+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:47:53.220+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:47:53.241+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.069 seconds
[2023-07-26T06:48:23.537+0000] {processor.py:154} INFO - Started process (PID=1361) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:48:23.538+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:48:23.539+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:48:23.539+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:48:23.639+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:48:23.637+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:48:23.640+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:48:23.665+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.133 seconds
[2023-07-26T06:48:54.335+0000] {processor.py:154} INFO - Started process (PID=1425) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:48:54.337+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:48:54.340+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:48:54.339+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:48:54.465+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:48:54.459+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:48:54.468+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:48:54.489+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.158 seconds
[2023-07-26T06:49:24.893+0000] {processor.py:154} INFO - Started process (PID=1490) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:49:24.894+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:49:24.895+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:49:24.895+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:49:24.933+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:49:24.931+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:49:24.934+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:49:24.949+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.060 seconds
[2023-07-26T06:49:55.388+0000] {processor.py:154} INFO - Started process (PID=1553) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:49:55.389+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:49:55.393+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:49:55.393+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:49:55.443+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:49:55.441+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:49:55.444+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:49:55.463+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.077 seconds
[2023-07-26T06:50:25.598+0000] {processor.py:154} INFO - Started process (PID=1617) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:50:25.601+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:50:25.604+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:50:25.603+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:50:25.648+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:50:25.647+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:50:25.649+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:50:25.665+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2023-07-26T06:50:55.980+0000] {processor.py:154} INFO - Started process (PID=1673) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:50:55.981+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:50:55.982+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:50:55.982+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:50:56.031+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:50:56.029+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:50:56.032+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:50:56.048+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2023-07-26T06:51:26.276+0000] {processor.py:154} INFO - Started process (PID=1737) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:51:26.279+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:51:26.280+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:51:26.280+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:51:26.328+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:51:26.327+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:51:26.329+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:51:26.344+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2023-07-26T06:51:56.411+0000] {processor.py:154} INFO - Started process (PID=1801) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:51:56.413+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:51:56.414+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:51:56.414+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:51:56.452+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:51:56.450+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:51:56.453+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:51:56.467+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2023-07-26T06:52:26.580+0000] {processor.py:154} INFO - Started process (PID=1865) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:52:26.581+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:52:26.583+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:52:26.583+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:52:26.621+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:52:26.619+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:52:26.622+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:52:26.640+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2023-07-26T06:52:56.847+0000] {processor.py:154} INFO - Started process (PID=1930) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:52:56.851+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:52:56.853+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:52:56.853+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:52:56.904+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:52:56.902+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:52:56.905+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:52:56.922+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.084 seconds
[2023-07-26T06:53:27.051+0000] {processor.py:154} INFO - Started process (PID=1985) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:53:27.052+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:53:27.053+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:53:27.053+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:53:27.092+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:53:27.090+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:53:27.093+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:53:27.108+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2023-07-26T06:53:57.370+0000] {processor.py:154} INFO - Started process (PID=2048) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:53:57.373+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:53:57.375+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:53:57.374+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:53:57.421+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:53:57.420+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:53:57.422+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:53:57.437+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2023-07-26T06:54:28.429+0000] {processor.py:154} INFO - Started process (PID=2112) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:54:28.431+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:54:28.432+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:54:28.432+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:54:28.475+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:54:28.473+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:54:28.475+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:54:28.492+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.067 seconds
[2023-07-26T06:55:03.168+0000] {processor.py:154} INFO - Started process (PID=2139) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:55:03.169+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:55:03.170+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:55:03.170+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:55:03.217+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:55:03.215+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:55:03.218+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:55:03.238+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.073 seconds
[2023-07-26T06:55:33.885+0000] {processor.py:154} INFO - Started process (PID=2194) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:55:33.887+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:55:33.888+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:55:33.888+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:55:33.933+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:55:33.931+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:55:33.934+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:55:33.960+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-07-26T06:56:04.677+0000] {processor.py:154} INFO - Started process (PID=2258) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:56:04.678+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:56:04.679+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:56:04.679+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:56:04.719+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:56:04.717+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:56:04.719+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:56:04.741+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.067 seconds
[2023-07-26T06:56:35.296+0000] {processor.py:154} INFO - Started process (PID=2322) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:56:35.298+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:56:35.299+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:56:35.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:56:35.364+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:56:35.362+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:56:35.364+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:56:35.389+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.098 seconds
[2023-07-26T06:57:05.703+0000] {processor.py:154} INFO - Started process (PID=2386) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:57:05.704+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:57:05.705+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:57:05.705+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:57:05.743+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:57:05.742+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:57:05.744+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:57:05.758+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.058 seconds
[2023-07-26T06:57:35.803+0000] {processor.py:154} INFO - Started process (PID=2449) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:57:35.806+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:57:35.808+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:57:35.807+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:57:35.859+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:57:35.858+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:57:35.860+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:57:35.875+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.077 seconds
[2023-07-26T06:58:06.366+0000] {processor.py:154} INFO - Started process (PID=2512) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:58:06.369+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:58:06.370+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:58:06.370+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:58:06.418+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:58:06.416+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:58:06.418+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:58:06.434+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2023-07-26T06:58:36.895+0000] {processor.py:154} INFO - Started process (PID=2575) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:58:36.896+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:58:36.897+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:58:36.897+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:58:36.933+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:58:36.931+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:58:36.942+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:58:36.957+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2023-07-26T06:59:07.311+0000] {processor.py:154} INFO - Started process (PID=2630) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:59:07.313+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:59:07.315+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:59:07.314+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:59:07.358+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:59:07.356+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:59:07.359+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:59:07.375+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.067 seconds
[2023-07-26T06:59:37.723+0000] {processor.py:154} INFO - Started process (PID=2694) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T06:59:37.726+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T06:59:37.727+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:59:37.727+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T06:59:37.843+0000] {logging_mixin.py:120} INFO - [2023-07-26T06:59:37.831+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T06:59:37.844+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T06:59:37.873+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.153 seconds
[2023-07-26T07:00:08.750+0000] {processor.py:154} INFO - Started process (PID=2758) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:00:08.751+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:00:08.753+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:00:08.752+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:00:08.806+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:00:08.804+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:00:08.806+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:00:08.830+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.084 seconds
[2023-07-26T07:00:39.333+0000] {processor.py:154} INFO - Started process (PID=2823) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:00:39.334+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:00:39.335+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:00:39.335+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:00:39.374+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:00:39.372+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:00:39.374+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:00:39.389+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.059 seconds
[2023-07-26T07:01:09.697+0000] {processor.py:154} INFO - Started process (PID=2887) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:01:09.698+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:01:09.699+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:01:09.699+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:01:09.740+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:01:09.738+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:01:09.741+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:01:09.763+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.069 seconds
[2023-07-26T07:01:40.334+0000] {processor.py:154} INFO - Started process (PID=2951) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:01:40.335+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:01:40.337+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:01:40.337+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:01:40.430+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:01:40.427+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:01:40.431+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:01:40.449+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.118 seconds
[2023-07-26T07:02:11.000+0000] {processor.py:154} INFO - Started process (PID=3006) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:02:11.001+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:02:11.003+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:02:11.002+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:02:11.044+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:02:11.042+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:02:11.045+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:02:11.060+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2023-07-26T07:02:41.428+0000] {processor.py:154} INFO - Started process (PID=3070) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:02:41.431+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:02:41.433+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:02:41.433+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:02:41.479+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:02:41.478+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:02:41.480+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:02:41.495+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2023-07-26T07:03:11.996+0000] {processor.py:154} INFO - Started process (PID=3135) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:03:11.998+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:03:12.000+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:03:11.999+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:03:12.051+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:03:12.048+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:03:12.052+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:03:12.067+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-07-26T07:03:42.485+0000] {processor.py:154} INFO - Started process (PID=3199) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:03:42.488+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:03:42.490+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:03:42.490+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:03:42.545+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:03:42.544+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:03:42.546+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:03:42.563+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.084 seconds
[2023-07-26T07:04:12.853+0000] {processor.py:154} INFO - Started process (PID=3264) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:04:12.855+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:04:12.857+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:04:12.857+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:04:12.900+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:04:12.898+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:04:12.900+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:04:12.917+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.070 seconds
[2023-07-26T07:04:43.100+0000] {processor.py:154} INFO - Started process (PID=3329) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:04:43.102+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:04:43.102+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:04:43.102+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:04:43.142+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:04:43.141+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:04:43.143+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:04:43.160+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.063 seconds
[2023-07-26T07:05:13.434+0000] {processor.py:154} INFO - Started process (PID=3384) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:05:13.436+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:05:13.437+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:05:13.437+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:05:13.487+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:05:13.485+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:05:13.488+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:05:13.517+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.086 seconds
[2023-07-26T07:05:43.863+0000] {processor.py:154} INFO - Started process (PID=3448) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:05:43.865+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:05:43.866+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:05:43.866+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:05:43.913+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:05:43.911+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:05:43.915+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:05:43.931+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2023-07-26T07:06:14.045+0000] {processor.py:154} INFO - Started process (PID=3512) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:06:14.048+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:06:14.050+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:06:14.050+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:06:14.112+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:06:14.109+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:06:14.113+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:06:14.132+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.096 seconds
[2023-07-26T07:06:44.649+0000] {processor.py:154} INFO - Started process (PID=3576) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:06:44.651+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:06:44.652+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:06:44.652+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:06:44.696+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:06:44.695+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:06:44.697+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:06:44.716+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.070 seconds
[2023-07-26T07:07:15.743+0000] {processor.py:154} INFO - Started process (PID=3640) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:07:15.746+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:07:15.748+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:07:15.747+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:07:15.816+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:07:15.814+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:07:15.817+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:07:15.838+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.100 seconds
[2023-07-26T07:07:45.963+0000] {processor.py:154} INFO - Started process (PID=3705) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:07:45.964+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:07:45.965+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:07:45.965+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:07:46.021+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:07:46.019+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:07:46.022+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:07:46.049+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.089 seconds
[2023-07-26T07:08:16.535+0000] {processor.py:154} INFO - Started process (PID=3760) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:08:16.538+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:08:16.539+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:08:16.539+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:08:16.585+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:08:16.584+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:08:16.586+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:08:16.601+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2023-07-26T07:08:46.673+0000] {processor.py:154} INFO - Started process (PID=3825) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:08:46.675+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:08:46.677+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:08:46.677+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:08:46.722+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:08:46.721+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:08:46.723+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:08:46.738+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.072 seconds
[2023-07-26T07:09:16.960+0000] {processor.py:154} INFO - Started process (PID=3889) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:09:16.961+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:09:16.963+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:09:16.962+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:09:17.008+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:09:17.007+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:09:17.008+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:09:17.023+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.069 seconds
[2023-07-26T07:09:47.293+0000] {processor.py:154} INFO - Started process (PID=3953) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:09:47.294+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:09:47.295+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:09:47.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:09:47.331+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:09:47.329+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:09:47.332+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:09:47.346+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.057 seconds
[2023-07-26T07:10:17.545+0000] {processor.py:154} INFO - Started process (PID=4017) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:10:17.547+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:10:17.549+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:10:17.548+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:10:17.596+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:10:17.594+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:10:17.597+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:10:17.612+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.072 seconds
[2023-07-26T07:10:47.769+0000] {processor.py:154} INFO - Started process (PID=4081) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:10:47.771+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:10:47.772+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:10:47.771+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:10:47.808+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:10:47.807+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:10:47.809+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:10:47.825+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.058 seconds
[2023-07-26T07:11:18.063+0000] {processor.py:154} INFO - Started process (PID=4136) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:11:18.066+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:11:18.068+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:11:18.068+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:11:18.114+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:11:18.112+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:11:18.115+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:11:18.130+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2023-07-26T07:11:48.382+0000] {processor.py:154} INFO - Started process (PID=4200) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:11:48.384+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:11:48.385+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:11:48.385+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:11:48.425+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:11:48.423+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:11:48.426+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:11:48.441+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2023-07-26T07:12:18.635+0000] {processor.py:154} INFO - Started process (PID=4264) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:12:18.636+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:12:18.637+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:12:18.637+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:12:18.674+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:12:18.673+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:12:18.676+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:12:18.691+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.058 seconds
[2023-07-26T07:12:48.949+0000] {processor.py:154} INFO - Started process (PID=4328) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:12:48.952+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:12:48.954+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:12:48.954+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:12:49.003+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:12:49.002+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:12:49.004+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:12:49.018+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.075 seconds
[2023-07-26T07:13:19.154+0000] {processor.py:154} INFO - Started process (PID=4392) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:13:19.156+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:13:19.157+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:13:19.157+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:13:19.210+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:13:19.208+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:13:19.211+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:13:19.226+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-07-26T07:13:49.384+0000] {processor.py:154} INFO - Started process (PID=4446) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:13:49.385+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:13:49.386+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:13:49.386+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:13:49.429+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:13:49.427+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:13:49.430+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:13:49.447+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.067 seconds
[2023-07-26T07:14:19.883+0000] {processor.py:154} INFO - Started process (PID=4510) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:14:19.885+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:14:19.885+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:14:19.885+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:14:19.926+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:14:19.924+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:14:19.927+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:14:19.944+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2023-07-26T07:14:50.149+0000] {processor.py:154} INFO - Started process (PID=4575) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:14:50.151+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:14:50.152+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:14:50.152+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:14:50.197+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:14:50.194+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:14:50.197+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:14:50.213+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.067 seconds
[2023-07-26T07:15:20.474+0000] {processor.py:154} INFO - Started process (PID=4639) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:15:20.478+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:15:20.480+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:15:20.480+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:15:20.532+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:15:20.531+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:15:20.533+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:15:20.548+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.082 seconds
[2023-07-26T07:15:50.774+0000] {processor.py:154} INFO - Started process (PID=4703) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:15:50.776+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:15:50.778+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:15:50.778+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:15:50.839+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:15:50.837+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:15:50.840+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:15:50.858+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.090 seconds
[2023-07-26T07:16:21.034+0000] {processor.py:154} INFO - Started process (PID=4765) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:16:21.036+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:16:21.037+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:16:21.037+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:16:21.077+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:16:21.076+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:16:21.079+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:16:21.096+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2023-07-26T07:16:51.187+0000] {processor.py:154} INFO - Started process (PID=4820) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:16:51.188+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:16:51.189+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:16:51.188+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:16:51.225+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:16:51.223+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:16:51.226+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:16:51.250+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.065 seconds
[2023-07-26T07:17:21.509+0000] {processor.py:154} INFO - Started process (PID=4884) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:17:21.512+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:17:21.513+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:17:21.513+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:17:21.565+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:17:21.563+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:17:21.566+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:17:21.582+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-07-26T07:17:51.816+0000] {processor.py:154} INFO - Started process (PID=4948) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:17:51.817+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:17:51.818+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:17:51.818+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:17:51.858+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:17:51.856+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:17:51.859+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:17:51.876+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.063 seconds
[2023-07-26T07:18:22.277+0000] {processor.py:154} INFO - Started process (PID=5012) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:18:22.279+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:18:22.283+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:18:22.283+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:18:22.327+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:18:22.325+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:18:22.328+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:18:22.348+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.073 seconds
[2023-07-26T07:18:53.352+0000] {processor.py:154} INFO - Started process (PID=5076) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:18:53.354+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:18:53.356+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:18:53.356+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:18:53.402+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:18:53.400+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:18:53.403+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:18:53.420+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.071 seconds
[2023-07-26T07:19:23.798+0000] {processor.py:154} INFO - Started process (PID=5140) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:19:23.800+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:19:23.801+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:19:23.801+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:19:23.857+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:19:23.854+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:19:23.858+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:19:23.876+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.082 seconds
[2023-07-26T07:19:54.142+0000] {processor.py:154} INFO - Started process (PID=5195) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:19:54.146+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:19:54.147+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:19:54.147+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:19:54.216+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:19:54.214+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:19:54.217+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:19:54.236+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.099 seconds
[2023-07-26T07:20:24.695+0000] {processor.py:154} INFO - Started process (PID=5259) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T07:20:24.698+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T07:20:24.699+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:20:24.699+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T07:20:24.745+0000] {logging_mixin.py:120} INFO - [2023-07-26T07:20:24.743+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T07:20:24.746+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T07:20:24.762+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.073 seconds
[2023-07-26T15:54:10.358+0000] {processor.py:154} INFO - Started process (PID=32) to work on /opt/airflow/dags/user_processing.py
[2023-07-26T15:54:10.375+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-07-26T15:54:10.376+0000] {logging_mixin.py:120} INFO - [2023-07-26T15:54:10.376+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-07-26T15:54:10.547+0000] {logging_mixin.py:120} INFO - [2023-07-26T15:54:10.541+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 10, in <module>
    task_id='create_table'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2023-07-26T15:54:10.550+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-07-26T15:54:10.582+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.232 seconds
